#!/usr/bin/env node
// Brand store: ~/.codebase-docs/brands/<slug>/{brand.json, logo.*, banners/*}
// Usage:
//   brand.mjs list
//   brand.mjs probe --website <url> --out <dir>      -> downloads logo/icon candidates + lists colour candidates (you look, then `set`)
//   brand.mjs probe --folder <dir> --out <dir>       -> same from a local folder (logos, banners, guidelines, colours)
//   brand.mjs set --name "Acme" [--logo file] [--primary "#hex"] [--accent "#hex"] [--font "Inter"]
//                 [--banner file ...] [--clear-banners] [--funding-text "Co-funded by …"] [--footer-text "…"]
//   brand.mjs export --company <slug> --out <dir>    -> <dir>/brand.css, brand.json, logo.*, banners/*
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const STORE = path.join(os.homedir(), ".codebase-docs", "brands");
const args = process.argv.slice(2);
const cmd = args[0];
const opt = (k, d) => { const i = args.indexOf(`--${k}`); return i === -1 ? d : args[i + 1]; };
const all = (k) => args.map((a, i) => a === `--${k}` ? args[i + 1] : null).filter(Boolean);
const has = (k) => args.includes(`--${k}`);
const slugify = (s) => s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

const DEFAULT = {
  name: "Default", slug: "default", logo: null, banners: [], fundingText: "", footerText: "",
  colors: { primary: "#1f3a5f", accent: "#e07a1f", ink: "#1a1a1a", muted: "#6b7280", paper: "#ffffff", surface: "#f4f6f8", line: "#d5dae1" },
  font: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
};
const readBrand = (slug) => {
  const f = path.join(STORE, slug || "", "brand.json");
  if (slug && fs.existsSync(f)) return { ...DEFAULT, ...JSON.parse(fs.readFileSync(f, "utf8")) };
  if (!slug || slug === "default") return DEFAULT;
  console.error(`brand not found: ${slug} (${f})`); process.exit(1);
};
const hexToRgb = (hex) => { const h = hex.replace("#", ""); const n = parseInt(h.length === 3 ? h.split("").map(c => c + c).join("") : h, 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; };
const mix = (hex, withHex, t) => { const a = hexToRgb(hex), b = hexToRgb(withHex); return "#" + a.map((v, i) => Math.round(v + (b[i] - v) * t).toString(16).padStart(2, "0")).join(""); };

function cssFor(b) {
  const c = { ...DEFAULT.colors, ...(b.colors || {}) }, f = { ...DEFAULT.font, ...(b.font || {}) };
  const fams = [...new Set([f.heading, f.body, f.mono])].map(n => `family=${encodeURIComponent(n).replace(/%20/g, "+")}:wght@400;500;600;700`).join("&");
  return `/* generated by codebase-docs brand.mjs — brand: ${b.name} */
@import url('https://fonts.googleapis.com/css2?${fams}&display=swap');
:root{
  --brand-name:"${b.name.replace(/"/g, "'")}";
  --primary:${c.primary}; --primary-soft:${mix(c.primary, c.paper, 0.88)}; --primary-deep:${mix(c.primary, "#000000", 0.25)};
  --accent:${c.accent}; --accent-soft:${mix(c.accent, c.paper, 0.85)};
  --ink:${c.ink}; --muted:${c.muted}; --paper:${c.paper}; --surface:${c.surface}; --line:${c.line};
  --fe:${c.primary}; --be:${mix(c.primary, "#000000", 0.35)}; --db:${c.accent}; --ext:${c.muted}; --user:${mix(c.accent, "#000000", 0.3)};
  --font-heading:"${f.heading}",system-ui,-apple-system,"Segoe UI",sans-serif;
  --font-body:"${f.body}",system-ui,-apple-system,"Segoe UI",sans-serif;
  --font-mono:"${f.mono}",ui-monospace,SFMono-Regular,Menlo,monospace;
}
`;
}

// ---------- colour candidates from text (css/html/scss/json/md)
const isGreyish = (hex) => { const [r, g, b] = hexToRgb(hex); const mx = Math.max(r, g, b), mn = Math.min(r, g, b); return mx - mn < 24 || mx < 40 || mn > 235; };
function colourCandidates(text) {
  const counts = new Map();
  for (const m of text.matchAll(/#([0-9a-f]{6}|[0-9a-f]{3})\b/gi)) { let h = m[1].toLowerCase(); if (h.length === 3) h = h.split("").map(c => c + c).join(""); h = "#" + h; if (!isGreyish(h)) counts.set(h, (counts.get(h) || 0) + 1); }
  for (const m of text.matchAll(/rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})/g)) { const h = "#" + [m[1], m[2], m[3]].map(v => (+v).toString(16).padStart(2, "0")).join(""); if (!isGreyish(h)) counts.set(h, (counts.get(h) || 0) + 1); }
  return [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10);
}
const IMG_RE = /\.(png|svg|jpe?g|webp|gif|pdf)$/i;
const BRANDY = /logo|brand|identity|sigla|antet|banner|eu[-_ ]|europ|uniunea|pnrr|funded|finan|guideline|manual|kit/i;

async function probeWebsite(url, out) {
  fs.mkdirSync(path.join(out, "candidates"), { recursive: true });
  const ua = { headers: { "user-agent": "Mozilla/5.0 (codebase-docs brand probe)" } };
  const res = await fetch(url, ua); const html = await res.text(); const base = new URL(res.url || url);
  const abs = (h) => { try { return new URL(h, base).href; } catch { return null; } };
  const found = [];
  const push = (kind, href, extra = "") => { const u = href && abs(href.replace(/&amp;/g, "&")); if (u && !found.some(f => f.url === u)) found.push({ kind, url: u, extra }); };
  for (const m of html.matchAll(/<link[^>]+>/gi)) { const t = m[0]; const rel = (t.match(/rel=["']([^"']+)/i) || [])[1] || ""; const href = (t.match(/href=["']([^"']+)/i) || [])[1]; if (/icon/i.test(rel) && href) push(`icon (${rel})`, href); }
  for (const m of html.matchAll(/<meta[^>]+>/gi)) { const t = m[0]; const prop = (t.match(/(?:property|name)=["']([^"']+)/i) || [])[1] || ""; const c = (t.match(/content=["']([^"']+)/i) || [])[1]; if (/og:image|twitter:image/i.test(prop) && c) push("og:image", c); if (/theme-color/i.test(prop) && c) found.push({ kind: "theme-color", url: null, extra: c }); }
  for (const m of html.matchAll(/<img[^>]+>/gi)) { const t = m[0]; const src = (t.match(/(?:data-src|src)=["']([^"']+)/i) || [])[1]; const alt = (t.match(/alt=["']([^"']*)/i) || [])[1] || ""; const cls = (t.match(/class=["']([^"']*)/i) || [])[1] || ""; if (src && !src.startsWith("data:") && (BRANDY.test(src) || BRANDY.test(alt) || BRANDY.test(cls))) push("img", src, alt); }
  for (const m of html.matchAll(/<svg[^>]*class=["'][^"']*logo[^"']*["'][\s\S]*?<\/svg>/gi)) { const f = path.join(out, "candidates", `inline-logo-${found.length}.svg`); fs.writeFileSync(f, m[0]); found.push({ kind: "inline svg logo", url: null, file: f }); }
  // stylesheets for colours
  let cssText = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map(m => m[1]).join("\n");
  const sheets = [...html.matchAll(/<link[^>]+rel=["'][^"']*stylesheet[^"']*["'][^>]*>/gi)].map(m => (m[0].match(/href=["']([^"']+)/i) || [])[1]).filter(Boolean).slice(0, 6);
  for (const s of sheets) { try { const r = await fetch(abs(s), ua); if (r.ok) cssText += "\n" + (await r.text()).slice(0, 400000); } catch {} }
  const colours = colourCandidates(cssText + "\n" + html);
  // download image candidates
  let i = 0; for (const f of found) { if (!f.url || i >= 10) continue; try { const r = await fetch(f.url, ua); const ct = r.headers.get("content-type") || ""; if (!r.ok || !/image|svg|octet/.test(ct)) { f.note = `skipped (${r.status} ${ct})`; continue; }
    const ext = ct.includes("svg") ? ".svg" : ct.includes("png") ? ".png" : ct.includes("webp") ? ".webp" : /jpe?g/.test(ct) ? ".jpg" : ct.includes("gif") ? ".gif" : ".png";
    f.file = path.join(out, "candidates", `${String(i++).padStart(2, "0")}-${f.kind.replace(/[^a-z]+/gi, "-")}${ext}`); fs.writeFileSync(f.file, Buffer.from(await r.arrayBuffer())); } catch (e) { f.note = `download failed: ${e.message}`; } }
  return { source: base.href, title: (html.match(/<title[^>]*>([^<]*)/i) || [])[1]?.trim(), images: found, colours };
}

function probeFolder(dir, out) {
  fs.mkdirSync(path.join(out, "candidates"), { recursive: true });
  const images = [], texts = []; const walk = (d, depth) => { if (depth > 4) return; for (const e of fs.readdirSync(d, { withFileTypes: true })) { if (/^(node_modules|\.git|dist|build|vendor)$/.test(e.name)) continue; const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p, depth + 1); else if (IMG_RE.test(e.name) && (BRANDY.test(p) || /(^|\/)(logo|logos|brand|branding|identity|banners?)\//i.test(p))) images.push(p); else if (/\.(css|scss|less|json|md|txt|html)$/i.test(e.name) && fs.statSync(p).size < 2e6) texts.push(p); } };
  walk(dir, 0);
  let i = 0; const copied = images.slice(0, 30).map(p => { const dst = path.join(out, "candidates", `${String(i++).padStart(2, "0")}-${path.basename(p)}`); fs.copyFileSync(p, dst); return { kind: /banner|eu|europ|pnrr|funded|finan/i.test(p) ? "banner?" : "logo?", url: null, source: p, file: dst }; });
  const colours = colourCandidates(texts.slice(0, 200).map(p => { try { return fs.readFileSync(p, "utf8"); } catch { return ""; } }).join("\n"));
  return { source: dir, images: copied, colours, textFiles: texts.filter(p => /brand|guideline|identity|manual|style/i.test(p)).slice(0, 10) };
}

if (cmd === "list") {
  if (!fs.existsSync(STORE)) { console.log("(no brands yet)"); process.exit(0); }
  for (const d of fs.readdirSync(STORE)) { const f = path.join(STORE, d, "brand.json"); if (!fs.existsSync(f)) continue; const b = JSON.parse(fs.readFileSync(f, "utf8"));
    console.log(`${b.slug}\t${b.name}\t${b.colors?.primary}\t${b.logo ? "logo" : "no-logo"}\t${(b.banners || []).length} banners`); }
} else if (cmd === "probe") {
  const out = opt("out"); if (!out) { console.error("--out required"); process.exit(1); }
  const r = opt("website") ? await probeWebsite(opt("website"), out) : opt("folder") ? probeFolder(path.resolve(opt("folder")), out) : null;
  if (!r) { console.error("probe needs --website <url> or --folder <dir>"); process.exit(1); }
  fs.writeFileSync(path.join(out, "probe.json"), JSON.stringify(r, null, 2));
  console.log(`# Brand probe — ${r.source}${r.title ? ` (${r.title})` : ""}\n\nImage candidates (look at each, pick the logo and any funding banners):`);
  for (const f of r.images) console.log(`- ${f.kind}: ${f.file || f.url || f.extra}${f.extra && f.file ? ` — ${f.extra}` : ""}${f.note ? ` — ${f.note}` : ""}${f.source ? ` — from ${f.source}` : ""}`);
  console.log(`\nColour candidates (most used, greys excluded): ${r.colours.map(([h, n]) => `${h} ×${n}`).join(", ") || "none found"}`);
  const tc = r.images.find(f => f.kind === "theme-color"); if (tc) console.log(`theme-color: ${tc.extra}`);
  if (r.textFiles?.length) console.log(`\nGuideline-like files worth reading: ${r.textFiles.join(", ")}`);
  console.log(`\nSummary written to ${path.join(out, "probe.json")}`);
} else if (cmd === "set") {
  const name = opt("name"); if (!name) { console.error("--name required"); process.exit(1); }
  const slug = slugify(name); if (!slug || slug === "default") { console.error(`"${name}" is reserved; choose the real company name`); process.exit(1); }
  const dir = path.join(STORE, slug); fs.mkdirSync(path.join(dir, "banners"), { recursive: true });
  const prev = fs.existsSync(path.join(dir, "brand.json")) ? JSON.parse(fs.readFileSync(path.join(dir, "brand.json"), "utf8")) : {};
  const b = { ...DEFAULT, ...prev, name, slug, colors: { ...DEFAULT.colors, ...(prev.colors || {}) }, font: { ...DEFAULT.font, ...(prev.font || {}) }, banners: [...(prev.banners || [])] };
  const logo = opt("logo");
  if (logo) { const ext = path.extname(logo).toLowerCase() || ".png"; fs.copyFileSync(logo, path.join(dir, `logo${ext}`)); b.logo = `logo${ext}`; }
  if (opt("primary")) b.colors.primary = opt("primary");
  if (opt("accent")) b.colors.accent = opt("accent");
  if (opt("font")) { b.font.heading = opt("font"); b.font.body = opt("font"); }
  if (has("clear-banners")) { b.banners = []; for (const f of fs.readdirSync(path.join(dir, "banners"))) fs.unlinkSync(path.join(dir, "banners", f)); }
  for (const src of all("banner")) { const dst = `banners/${slugify(path.basename(src, path.extname(src)))}${path.extname(src).toLowerCase()}`; fs.copyFileSync(src, path.join(dir, dst)); if (!b.banners.some(x => x.file === dst)) b.banners.push({ file: dst, alt: path.basename(src, path.extname(src)) }); }
  if (opt("funding-text") !== undefined) b.fundingText = opt("funding-text");
  if (opt("footer-text") !== undefined) b.footerText = opt("footer-text");
  b.updatedAt = new Date().toISOString();
  fs.writeFileSync(path.join(dir, "brand.json"), JSON.stringify(b, null, 2));
  console.log(`saved ${path.join(dir, "brand.json")}${b.logo ? ` (logo: ${b.logo})` : ""}${b.banners.length ? ` (${b.banners.length} banners)` : ""}`);
} else if (cmd === "export") {
  const b = readBrand(opt("company", "default")); const out = opt("out"); if (!out) { console.error("--out required"); process.exit(1); }
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, "brand.css"), cssFor(b));
  fs.writeFileSync(path.join(out, "brand.json"), JSON.stringify(b, null, 2));
  if (b.logo) fs.copyFileSync(path.join(STORE, b.slug, b.logo), path.join(out, b.logo));
  if (b.banners?.length) { fs.mkdirSync(path.join(out, "banners"), { recursive: true }); for (const x of b.banners) fs.copyFileSync(path.join(STORE, b.slug, x.file), path.join(out, x.file)); }
  console.log(`exported brand "${b.name}" -> ${out}/brand.css${b.logo ? `, ${b.logo}` : " (no logo)"}${b.banners?.length ? `, ${b.banners.length} banners` : ""}`);
} else {
  console.error("usage: brand.mjs list | probe --website <url>|--folder <dir> --out <dir> | set --name .. [--logo ..] [--primary ..] [--accent ..] [--font ..] [--banner ..] [--funding-text ..] [--footer-text ..] | export --company <slug> --out <dir>");
  process.exit(1);
}
