#!/usr/bin/env node
// Build the documentation index: <docs>/README.md, <docs>/index.html (static site entry), <docs>/glossary.md,
// and <docs>/assets/modules.html/.png (cross-module diagram from each stamp's "calls").
// Usage: docs-index.mjs <docs-dir> <root-dir> [--brand-dir <dir>] [--no-diagram]
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const here = path.dirname(fileURLToPath(import.meta.url));
const [docsDir, root] = process.argv.slice(2);
if (!docsDir || !root) { console.error("usage: docs-index.mjs <docs-dir> <root-dir> [--brand-dir dir] [--no-diagram]"); process.exit(1); }
const args = process.argv.slice(4); const opt = (k, d) => { const i = args.indexOf(`--${k}`); return i === -1 ? d : args[i + 1]; };
const stale = JSON.parse(execFileSync("node", [path.join(here, "check-stale.mjs"), docsDir, root, "--json"], { encoding: "utf8" }));
const mods = [];
for (const d of fs.readdirSync(docsDir, { withFileTypes: true })) {
  if (!d.isDirectory() || d.name.startsWith(".") || d.name === "assets") continue;
  const mdf = [path.join(docsDir, d.name, `${d.name}.md`), ...fs.readdirSync(path.join(docsDir, d.name)).filter(f => f.endsWith(".md") && !f.includes(".onepager")).map(f => path.join(docsDir, d.name, f))].find(f => fs.existsSync(f));
  if (!mdf) continue;
  const src = fs.readFileSync(mdf, "utf8"); const m = src.match(/<!--\s*codebase-docs\s+(\{[\s\S]*?\})\s*-->/); let stamp = {}; try { stamp = m ? JSON.parse(m[1]) : {}; } catch {}
  const st = stale.find(s => s.file === mdf) || { status: "unstamped" };
  const summary = (src.split(/^## /m)[1] || "").split("\n").slice(1).join(" ").replace(/[#*`]/g, "").trim().slice(0, 220);
  const gloss = []; const gsec = src.split(/^## \d+\.\s*(?:Glossary|Glosar|Glossar|Glossaire|Glosario)\s*$/mi)[1];
  if (gsec) for (const l of gsec.split(/^## /m)[0].split("\n")) { const g = l.match(/^-\s+\*\*(.+?)\*\*\s*[:—-]\s*(.+)$/); if (g) gloss.push({ term: g[1].trim(), def: g[2].trim(), module: d.name }); }
  const base = path.basename(mdf, ".md");
  mods.push({ dir: d.name, base, title: stamp.title || base, subtitle: stamp.subtitle || "", generated: stamp.generated || "", status: st.status, changes: st.changes || [], repos: stamp.repos || {}, calls: stamp.calls || [], summary, gloss,
    pdf: fs.existsSync(path.join(docsDir, d.name, `${base}.pdf`)) ? `${d.name}/${base}.pdf` : null, html: fs.existsSync(path.join(docsDir, d.name, `${base}.html`)) ? `${d.name}/${base}.html` : null,
    onepager: fs.existsSync(path.join(docsDir, d.name, `${base}.onepager.pdf`)) ? `${d.name}/${base}.onepager.pdf` : null });
}
mods.sort((a, b) => a.dir.localeCompare(b.dir));
const badge = (m) => m.status === "fresh" ? "✅ up to date" : m.status === "stale" ? `⚠️ stale (${m.changes.map(c => c.error ? `${c.repo}: ${c.error}` : `${c.repo}: ${c.files.length} committed${c.uncommitted?.length ? `, ${c.uncommitted.length} uncommitted` : ""}`).join("; ")})` : `❓ ${m.status}`;
const today = new Date().toISOString().slice(0, 10);
// README.md
let md = `# Documentation index\n\nGenerated by codebase-docs on ${today}. Run \`/codebase-docs:document <module>\` to update a module; \`--check\` refreshes this index only.\n\n| Module | Document | Generated | Status | Repos |\n|---|---|---|---|---|\n`;
for (const m of mods) md += `| **${m.title}** | ${m.pdf ? `[PDF](${m.pdf})` : "—"}${m.onepager ? ` · [one-pager](${m.onepager})` : ""} · [md](${m.dir}/${m.base}.md) | ${m.generated || "—"} | ${badge(m)} | ${Object.entries(m.repos).map(([r, v]) => `${r} \`${(v.sha || "").slice(0, 7)}\``).join(", ") || "—"} |\n`;
if (mods.some(m => m.summary)) { md += `\n## Summaries\n\n`; for (const m of mods) if (m.summary) md += `**${m.title}** — ${m.summary}\n\n`; }
if (mods.some(m => m.calls.length)) md += `\n## Module map\n\n![Modules and their dependencies](assets/modules.png)\n\n` + mods.filter(m => m.calls.length).map(m => `- **${m.dir}** → ${m.calls.join(", ")}`).join("\n") + "\n";
md += `\nSee [glossary.md](glossary.md) for the shared vocabulary.\n`;
fs.writeFileSync(path.join(docsDir, "README.md"), md);
// glossary.md
const byTerm = new Map(); for (const m of mods) for (const g of m.gloss) { const k = g.term.toLowerCase(); if (!byTerm.has(k)) byTerm.set(k, []); byTerm.get(k).push(g); }
let gl = `# Glossary\n\nCollected from every module document (${today}). A term defined differently in two modules is listed with both definitions — align them in the documents.\n\n`;
for (const k of [...byTerm.keys()].sort()) { const es = byTerm.get(k); const defs = [...new Set(es.map(e => e.def))];
  gl += defs.length === 1 ? `- **${es[0].term}** — ${defs[0]} *(${[...new Set(es.map(e => e.module))].join(", ")})*\n` : `- **${es[0].term}** — ⚠️ differs:\n${es.map(e => `  - ${e.module}: ${e.def}`).join("\n")}\n`; }
fs.writeFileSync(path.join(docsDir, "glossary.md"), gl);
// index.html (static site entry)
const brandDir = opt("brand-dir", mods[0] ? path.join(docsDir, mods[0].dir, "assets", "brand") : null);
const brandCss = brandDir && fs.existsSync(path.join(brandDir, "brand.css")) ? fs.readFileSync(path.join(brandDir, "brand.css"), "utf8") : "";
const brand = brandDir && fs.existsSync(path.join(brandDir, "brand.json")) ? JSON.parse(fs.readFileSync(path.join(brandDir, "brand.json"), "utf8")) : {};
const logo = brand.logo && brandDir ? `<img src="${path.relative(docsDir, path.join(brandDir, brand.logo)).split(path.sep).join("/")}" alt="${brand.name || ""}" style="height:32px">` : `<strong>${brand.name || ""}</strong>`;
const card = (m) => `<article class="card"><h2>${m.title}</h2><p class="sub">${m.subtitle}</p><p>${m.summary}</p><p class="meta">${m.generated} · ${badge(m)}</p><p class="links">${m.html ? `<a href="${m.html}">Read online</a>` : ""}${m.pdf ? `<a href="${m.pdf}">PDF</a>` : ""}${m.onepager ? `<a href="${m.onepager}">One-pager</a>` : ""}<a href="${m.dir}/${m.base}.md">Markdown</a></p></article>`;
fs.writeFileSync(path.join(docsDir, "index.html"), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${brand.name ? brand.name + " — " : ""}Documentation</title><style>${brandCss}
body{margin:0;font-family:var(--font-body,system-ui);color:var(--ink,#1a1a1a);background:var(--surface,#f4f6f8)}header{background:var(--paper,#fff);border-bottom:1px solid var(--line,#ddd);padding:16px 24px;display:flex;align-items:center;gap:16px}header h1{font:600 18px var(--font-heading,system-ui);margin:0;color:var(--primary-deep,#123)}main{max-width:1100px;margin:24px auto;padding:0 16px;display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px}.card{background:var(--paper,#fff);border:1px solid var(--line,#ddd);border-radius:10px;padding:18px}.card h2{font:600 17px var(--font-heading,system-ui);margin:0 0 4px;color:var(--primary,#123)}.sub{color:var(--muted,#666);margin:0 0 10px;font-size:13px}.meta{font-size:12px;color:var(--muted,#666)}.links a{display:inline-block;margin-right:12px;color:var(--primary,#123);font-weight:600;text-decoration:none}footer{text-align:center;color:var(--muted,#666);font-size:12px;padding:24px}.map{grid-column:1/-1;background:var(--paper,#fff);border:1px solid var(--line,#ddd);border-radius:10px;padding:18px;text-align:center}.map img{max-width:100%}</style></head><body><header>${logo}<h1>Technical documentation</h1></header><main>${mods.map(card).join("")}${mods.some(m => m.calls.length) ? `<section class="map"><img src="assets/modules.png" alt="Modules and their dependencies"></section>` : ""}</main><footer>Generated ${today} · <a href="glossary.md">glossary</a></footer></body></html>`);
// cross-module diagram
if (!args.includes("--no-diagram") && mods.some(m => m.calls.length)) {
  fs.mkdirSync(path.join(docsDir, "assets"), { recursive: true });
  const names = [...new Set(mods.flatMap(m => [m.dir, ...m.calls]))];
  const cols = Math.min(4, Math.max(2, Math.ceil(Math.sqrt(names.length))));
  const nodes = names.map((n, i) => `<div class="node ${mods.some(m => m.dir === n) ? "node--be" : "node--ext"}" id="m-${n.replace(/[^a-z0-9]/gi, "-")}" style="grid-column:${(i % cols) + 1};grid-row:${Math.floor(i / cols) + 1};max-width:380px"><span class="kind">${mods.some(m => m.dir === n) ? "documented" : "not documented"}</span><span class="name">${n}</span></div>`).join("");
  const arrows = mods.flatMap(m => m.calls.map((c, i) => `connect('#m-${m.dir.replace(/[^a-z0-9]/gi, "-")}','#m-${c.replace(/[^a-z0-9]/gi, "-")}',{offset:${(i % 3 - 1) * 14},at:${0.35 + (i % 3) * 0.15}});`)).join("\n");
  let tpl = fs.readFileSync(path.join(here, "..", "templates", "diagram.html"), "utf8");
  const rows = Math.ceil(names.length / cols); const H = 170 + rows * 130;
  tpl = tpl.replace("Diagram title", "Module map").replace("One line that says what this diagram shows", "Documented modules and the modules they call")
    .replace(/data-width="\d+" data-height="\d+"/, `data-width="1400" data-height="${H}"`).replace(/--w:\d+px;--h:\d+px/, `--w:1400px;--h:${H}px`)
    .replace(/<!-- ===== compose the diagram here[\s\S]*?-->/, `<div style="display:grid;grid-template-columns:repeat(${cols},1fr);gap:70px 90px;margin-top:10px">${nodes}</div>`)
    .replace("// connect('#user','#web',{label:'opens /orders'});", arrows).replace("{{brand_name}}", brand.name || "").replace('href="../brand/brand.css"', `href="${brandDir ? path.relative(path.join(docsDir, "assets"), path.join(brandDir, "brand.css")).split(path.sep).join("/") : ""}"`);
  fs.writeFileSync(path.join(docsDir, "assets", "modules.html"), tpl);
  try { execFileSync("bash", [path.join(here, "render-diagram.sh"), path.join(docsDir, "assets", "modules.html")], { stdio: "ignore" }); } catch { console.error("module diagram render failed (Chrome?)"); }
}
console.log(`index: ${path.join(docsDir, "README.md")}, ${path.join(docsDir, "index.html")}, ${path.join(docsDir, "glossary.md")} — ${mods.length} module(s): ${mods.map(m => `${m.dir} ${m.status}`).join(", ")}`);
